// File generated by FlutterFire CLI and manually updated for project: qlchitieu-9cf13
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDksrL7suPiioDYn_UHTErgNb179C9Vf70',
    appId: '1:155696207509:web:61d0233633857e4e476d9c',
    messagingSenderId: '155696207509',
    projectId: 'qlchitieu-9cf13',
    authDomain: 'qlchitieu-9cf13.firebaseapp.com',
    storageBucket: 'qlchitieu-9cf13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDksrL7suPiioDYn_UHTErgNb179C9Vf70',
    appId: '1:155696207509:android:6ed45e94850ddff9476d9c',
    messagingSenderId: '155696207509',
    projectId: 'qlchitieu-9cf13',
    storageBucket: 'qlchitieu-9cf13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDksrL7suPiioDYn_UHTErgNb179C9Vf70',
    appId: '1:155696207509:ios:9e7019a16f6b5b4e476d9c',
    messagingSenderId: '155696207509',
    projectId: 'qlchitieu-9cf13',
    storageBucket: 'qlchitieu-9cf13.firebasestorage.app',
    iosBundleId: 'com.example.screensetting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDksrL7suPiioDYn_UHTErgNb179C9Vf70',
    appId: '1:155696207509:ios:9e7019a16f6b5b4e476d9c',
    messagingSenderId: '155696207509',
    projectId: 'qlchitieu-9cf13',
    storageBucket: 'qlchitieu-9cf13.firebasestorage.app',
    iosBundleId: 'com.example.screensetting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDksrL7suPiioDYn_UHTErgNb179C9Vf70',
    appId: '1:155696207509:web:61d0233633857e4e476d9c',
    messagingSenderId: '155696207509',
    projectId: 'qlchitieu-9cf13',
    authDomain: 'qlchitieu-9cf13.firebaseapp.com',
    storageBucket: 'qlchitieu-9cf13.firebasestorage.app',
  );
}